import { GoogleAnalytics } from "@next/third-parties/google";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const helvetica = localFont({
  src: "./fonts/Helvetica.ttf",
  variable: "--font-helvetica",
  weight: "300 400 500 600 700",
});

const streamer = localFont({
  src: "./fonts/Streamster.ttf",
  variable: "--font-streamer",
  weight: "400",
});

export const metadata: Metadata = {
  title: "A última dança",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  authors: {
    name: "Eduardo Alves",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="scroll-smooth">
      <GoogleAnalytics gaId="G-65F6D3FMH6" />
      <body
        className={`${helvetica.variable} ${streamer.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
